apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: px-wp-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: px-wordpress-sc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi