apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: px-mysql-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: px-mysql-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi